package bz.sunlight.entity;

import java.io.Serializable;

public class Api implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.Id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.Name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.Http_Method
   *
   * @mbggenerated
   */
  private String httpMethod;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.Url
   *
   * @mbggenerated
   */
  private String url;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.Enterprise_Id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table api
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.Id
   *
   * @return the value of api.Id
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.Id
   *
   * @param id the value for api.Id
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.Name
   *
   * @return the value of api.Name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.Name
   *
   * @param name the value for api.Name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.Http_Method
   *
   * @return the value of api.Http_Method
   * @mbggenerated
   */
  public String getHttpMethod() {
    return httpMethod;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.Http_Method
   *
   * @param httpMethod the value for api.Http_Method
   * @mbggenerated
   */
  public void setHttpMethod(String httpMethod) {
    this.httpMethod = httpMethod == null ? null : httpMethod.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.Url
   *
   * @return the value of api.Url
   * @mbggenerated
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.Url
   *
   * @param url the value for api.Url
   * @mbggenerated
   */
  public void setUrl(String url) {
    this.url = url == null ? null : url.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.Enterprise_Id
   *
   * @return the value of api.Enterprise_Id
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.Enterprise_Id
   *
   * @param enterpriseId the value for api.Enterprise_Id
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }
}