package bz.sunlight.entity;

import java.io.Serializable;

public class Api implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.http_method
   *
   * @mbggenerated
   */
  private String httpMethod;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column api.url
   *
   * @mbggenerated
   */
  private String url;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table api
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.id
   *
   * @return the value of api.id
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.id
   *
   * @param id the value for api.id
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.name
   *
   * @return the value of api.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.name
   *
   * @param name the value for api.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.http_method
   *
   * @return the value of api.http_method
   *
   * @mbggenerated
   */
  public String getHttpMethod() {
    return httpMethod;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.http_method
   *
   * @param httpMethod the value for api.http_method
   *
   * @mbggenerated
   */
  public void setHttpMethod(String httpMethod) {
    this.httpMethod = httpMethod == null ? null : httpMethod.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column api.url
   *
   * @return the value of api.url
   *
   * @mbggenerated
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column api.url
   *
   * @param url the value for api.url
   *
   * @mbggenerated
   */
  public void setUrl(String url) {
    this.url = url == null ? null : url.trim();
  }
}