package bz.sunlight.entity;

import java.io.Serializable;

public class OperationApi implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation_api.Operation_Id
   *
   * @mbggenerated
   */
  private String operationId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation_api.Api_Id
   *
   * @mbggenerated
   */
  private String apiId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation_api.Operation_Id
   *
   * @return the value of operation_api.Operation_Id
   * @mbggenerated
   */
  public String getOperationId() {
    return operationId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation_api.Operation_Id
   *
   * @param operationId the value for operation_api.Operation_Id
   * @mbggenerated
   */
  public void setOperationId(String operationId) {
    this.operationId = operationId == null ? null : operationId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation_api.Api_Id
   *
   * @return the value of operation_api.Api_Id
   * @mbggenerated
   */
  public String getApiId() {
    return apiId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation_api.Api_Id
   *
   * @param apiId the value for operation_api.Api_Id
   * @mbggenerated
   */
  public void setApiId(String apiId) {
    this.apiId = apiId == null ? null : apiId.trim();
  }
}