package bz.sunlight.entity;

import java.io.Serializable;

public class Operation implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.code
   *
   * @mbggenerated
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.page_id
   *
   * @mbggenerated
   */
  private String pageId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.id
   *
   * @return the value of operation.id
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.id
   *
   * @param id the value for operation.id
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.code
   *
   * @return the value of operation.code
   *
   * @mbggenerated
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.code
   *
   * @param code the value for operation.code
   *
   * @mbggenerated
   */
  public void setCode(String code) {
    this.code = code == null ? null : code.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.name
   *
   * @return the value of operation.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.name
   *
   * @param name the value for operation.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.page_id
   *
   * @return the value of operation.page_id
   *
   * @mbggenerated
   */
  public String getPageId() {
    return pageId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.page_id
   *
   * @param pageId the value for operation.page_id
   *
   * @mbggenerated
   */
  public void setPageId(String pageId) {
    this.pageId = pageId == null ? null : pageId.trim();
  }
}