package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.List;

public class OperationApiExample {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  private Integer limit;

  private Integer offset;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public OperationApiExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getOffset() {
    return offset;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andOperationIdIsNull() {
      addCriterion("Operation_Id is null");
      return (Criteria) this;
    }

    public Criteria andOperationIdIsNotNull() {
      addCriterion("Operation_Id is not null");
      return (Criteria) this;
    }

    public Criteria andOperationIdEqualTo(String value) {
      addCriterion("Operation_Id =", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdNotEqualTo(String value) {
      addCriterion("Operation_Id <>", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdGreaterThan(String value) {
      addCriterion("Operation_Id >", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdGreaterThanOrEqualTo(String value) {
      addCriterion("Operation_Id >=", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdLessThan(String value) {
      addCriterion("Operation_Id <", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdLessThanOrEqualTo(String value) {
      addCriterion("Operation_Id <=", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdLike(String value) {
      addCriterion("Operation_Id like", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdNotLike(String value) {
      addCriterion("Operation_Id not like", value, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdIn(List<String> values) {
      addCriterion("Operation_Id in", values, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdNotIn(List<String> values) {
      addCriterion("Operation_Id not in", values, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdBetween(String value1, String value2) {
      addCriterion("Operation_Id between", value1, value2, "operationId");
      return (Criteria) this;
    }

    public Criteria andOperationIdNotBetween(String value1, String value2) {
      addCriterion("Operation_Id not between", value1, value2, "operationId");
      return (Criteria) this;
    }

    public Criteria andApiIdIsNull() {
      addCriterion("Api_Id is null");
      return (Criteria) this;
    }

    public Criteria andApiIdIsNotNull() {
      addCriterion("Api_Id is not null");
      return (Criteria) this;
    }

    public Criteria andApiIdEqualTo(String value) {
      addCriterion("Api_Id =", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdNotEqualTo(String value) {
      addCriterion("Api_Id <>", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdGreaterThan(String value) {
      addCriterion("Api_Id >", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdGreaterThanOrEqualTo(String value) {
      addCriterion("Api_Id >=", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdLessThan(String value) {
      addCriterion("Api_Id <", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdLessThanOrEqualTo(String value) {
      addCriterion("Api_Id <=", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdLike(String value) {
      addCriterion("Api_Id like", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdNotLike(String value) {
      addCriterion("Api_Id not like", value, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdIn(List<String> values) {
      addCriterion("Api_Id in", values, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdNotIn(List<String> values) {
      addCriterion("Api_Id not in", values, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdBetween(String value1, String value2) {
      addCriterion("Api_Id between", value1, value2, "apiId");
      return (Criteria) this;
    }

    public Criteria andApiIdNotBetween(String value1, String value2) {
      addCriterion("Api_Id not between", value1, value2, "apiId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table operation_api
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table operation_api
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}