package bz.sunlight.entity;

import java.io.Serializable;

public class Operation implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.Id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.Code
   *
   * @mbggenerated
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.Name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.Page_Id
   *
   * @mbggenerated
   */
  private String pageId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column operation.Enterprise_Id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table operation
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.Id
   *
   * @return the value of operation.Id
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.Id
   *
   * @param id the value for operation.Id
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.Code
   *
   * @return the value of operation.Code
   * @mbggenerated
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.Code
   *
   * @param code the value for operation.Code
   * @mbggenerated
   */
  public void setCode(String code) {
    this.code = code == null ? null : code.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.Name
   *
   * @return the value of operation.Name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.Name
   *
   * @param name the value for operation.Name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.Page_Id
   *
   * @return the value of operation.Page_Id
   * @mbggenerated
   */
  public String getPageId() {
    return pageId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.Page_Id
   *
   * @param pageId the value for operation.Page_Id
   * @mbggenerated
   */
  public void setPageId(String pageId) {
    this.pageId = pageId == null ? null : pageId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column operation.Enterprise_Id
   *
   * @return the value of operation.Enterprise_Id
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column operation.Enterprise_Id
   *
   * @param enterpriseId the value for operation.Enterprise_Id
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }
}