package bz.sunlight.entity;

import java.io.Serializable;

public class Page implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.code
   *
   * @mbggenerated
   */
  private String code;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.pinyin
   *
   * @mbggenerated
   */
  private String pinyin;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.initial
   *
   * @mbggenerated
   */
  private String initial;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.url
   *
   * @mbggenerated
   */
  private String url;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.icon
   *
   * @mbggenerated
   */
  private String icon;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.weight
   *
   * @mbggenerated
   */
  private Integer weight;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.level
   *
   * @mbggenerated
   */
  private Integer level;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column page.parent_id
   *
   * @mbggenerated
   */
  private String parentId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table page
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.id
   *
   * @return the value of page.id
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.id
   *
   * @param id the value for page.id
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.code
   *
   * @return the value of page.code
   *
   * @mbggenerated
   */
  public String getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.code
   *
   * @param code the value for page.code
   *
   * @mbggenerated
   */
  public void setCode(String code) {
    this.code = code == null ? null : code.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.name
   *
   * @return the value of page.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.name
   *
   * @param name the value for page.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.pinyin
   *
   * @return the value of page.pinyin
   *
   * @mbggenerated
   */
  public String getPinyin() {
    return pinyin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.pinyin
   *
   * @param pinyin the value for page.pinyin
   *
   * @mbggenerated
   */
  public void setPinyin(String pinyin) {
    this.pinyin = pinyin == null ? null : pinyin.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.initial
   *
   * @return the value of page.initial
   *
   * @mbggenerated
   */
  public String getInitial() {
    return initial;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.initial
   *
   * @param initial the value for page.initial
   *
   * @mbggenerated
   */
  public void setInitial(String initial) {
    this.initial = initial == null ? null : initial.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.url
   *
   * @return the value of page.url
   *
   * @mbggenerated
   */
  public String getUrl() {
    return url;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.url
   *
   * @param url the value for page.url
   *
   * @mbggenerated
   */
  public void setUrl(String url) {
    this.url = url == null ? null : url.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.icon
   *
   * @return the value of page.icon
   *
   * @mbggenerated
   */
  public String getIcon() {
    return icon;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.icon
   *
   * @param icon the value for page.icon
   *
   * @mbggenerated
   */
  public void setIcon(String icon) {
    this.icon = icon == null ? null : icon.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.weight
   *
   * @return the value of page.weight
   *
   * @mbggenerated
   */
  public Integer getWeight() {
    return weight;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.weight
   *
   * @param weight the value for page.weight
   *
   * @mbggenerated
   */
  public void setWeight(Integer weight) {
    this.weight = weight;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.level
   *
   * @return the value of page.level
   *
   * @mbggenerated
   */
  public Integer getLevel() {
    return level;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.level
   *
   * @param level the value for page.level
   *
   * @mbggenerated
   */
  public void setLevel(Integer level) {
    this.level = level;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column page.parent_id
   *
   * @return the value of page.parent_id
   *
   * @mbggenerated
   */
  public String getParentId() {
    return parentId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column page.parent_id
   *
   * @param parentId the value for page.parent_id
   *
   * @mbggenerated
   */
  public void setParentId(String parentId) {
    this.parentId = parentId == null ? null : parentId.trim();
  }
}