package bz.sunlight.entity;

import java.io.Serializable;

public class Permission implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column permission.Role_Id
   *
   * @mbggenerated
   */
  private String roleId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column permission.Related_Id
   *
   * @mbggenerated
   */
  private String relatedId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column permission.Type
   *
   * @mbggenerated
   */
  private Integer type;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table permission
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column permission.Role_Id
   *
   * @return the value of permission.Role_Id
   * @mbggenerated
   */
  public String getRoleId() {
    return roleId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column permission.Role_Id
   *
   * @param roleId the value for permission.Role_Id
   * @mbggenerated
   */
  public void setRoleId(String roleId) {
    this.roleId = roleId == null ? null : roleId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column permission.Related_Id
   *
   * @return the value of permission.Related_Id
   * @mbggenerated
   */
  public String getRelatedId() {
    return relatedId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column permission.Related_Id
   *
   * @param relatedId the value for permission.Related_Id
   * @mbggenerated
   */
  public void setRelatedId(String relatedId) {
    this.relatedId = relatedId == null ? null : relatedId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column permission.Type
   *
   * @return the value of permission.Type
   * @mbggenerated
   */
  public Integer getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column permission.Type
   *
   * @param type the value for permission.Type
   * @mbggenerated
   */
  public void setType(Integer type) {
    this.type = type;
  }
}