package bz.sunlight.entity;

import java.io.Serializable;
import java.util.Date;

public class Role implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Create_Time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Creator
   *
   * @mbggenerated
   */
  private String creator;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Enterprise_Id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.Status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table role
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Id
   *
   * @return the value of role.Id
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Id
   *
   * @param id the value for role.Id
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Name
   *
   * @return the value of role.Name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Name
   *
   * @param name the value for role.Name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Create_Time
   *
   * @return the value of role.Create_Time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Create_Time
   *
   * @param createTime the value for role.Create_Time
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Creator
   *
   * @return the value of role.Creator
   * @mbggenerated
   */
  public String getCreator() {
    return creator;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Creator
   *
   * @param creator the value for role.Creator
   * @mbggenerated
   */
  public void setCreator(String creator) {
    this.creator = creator == null ? null : creator.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Enterprise_Id
   *
   * @return the value of role.Enterprise_Id
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Enterprise_Id
   *
   * @param enterpriseId the value for role.Enterprise_Id
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.Status
   *
   * @return the value of role.Status
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.Status
   *
   * @param status the value for role.Status
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }
}