package bz.sunlight.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class Role implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.creator_id
   *
   * @mbggenerated
   */
  private String creatorId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.creator_name
   *
   * @mbggenerated
   */
  private String creatorName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.modifier_id
   *
   * @mbggenerated
   */
  private String modifierId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.modifier_name
   *
   * @mbggenerated
   */
  private String modifierName;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.modify_time
   *
   * @mbggenerated
   */
  private Date modifyTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.enterprise_id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.read_only
   *
   * @mbggenerated
   */
  private Boolean readOnly;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.row_version
   *
   * @mbggenerated
   */
  private Timestamp rowVersion;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table role
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.id
   *
   * @return the value of role.id
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.id
   *
   * @param id the value for role.id
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.name
   *
   * @return the value of role.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.name
   *
   * @param name the value for role.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.creator_id
   *
   * @return the value of role.creator_id
   *
   * @mbggenerated
   */
  public String getCreatorId() {
    return creatorId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.creator_id
   *
   * @param creatorId the value for role.creator_id
   *
   * @mbggenerated
   */
  public void setCreatorId(String creatorId) {
    this.creatorId = creatorId == null ? null : creatorId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.creator_name
   *
   * @return the value of role.creator_name
   *
   * @mbggenerated
   */
  public String getCreatorName() {
    return creatorName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.creator_name
   *
   * @param creatorName the value for role.creator_name
   *
   * @mbggenerated
   */
  public void setCreatorName(String creatorName) {
    this.creatorName = creatorName == null ? null : creatorName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.create_time
   *
   * @return the value of role.create_time
   *
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.create_time
   *
   * @param createTime the value for role.create_time
   *
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.modifier_id
   *
   * @return the value of role.modifier_id
   *
   * @mbggenerated
   */
  public String getModifierId() {
    return modifierId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.modifier_id
   *
   * @param modifierId the value for role.modifier_id
   *
   * @mbggenerated
   */
  public void setModifierId(String modifierId) {
    this.modifierId = modifierId == null ? null : modifierId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.modifier_name
   *
   * @return the value of role.modifier_name
   *
   * @mbggenerated
   */
  public String getModifierName() {
    return modifierName;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.modifier_name
   *
   * @param modifierName the value for role.modifier_name
   *
   * @mbggenerated
   */
  public void setModifierName(String modifierName) {
    this.modifierName = modifierName == null ? null : modifierName.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.modify_time
   *
   * @return the value of role.modify_time
   *
   * @mbggenerated
   */
  public Date getModifyTime() {
    return modifyTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.modify_time
   *
   * @param modifyTime the value for role.modify_time
   *
   * @mbggenerated
   */
  public void setModifyTime(Date modifyTime) {
    this.modifyTime = modifyTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.enterprise_id
   *
   * @return the value of role.enterprise_id
   *
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.enterprise_id
   *
   * @param enterpriseId the value for role.enterprise_id
   *
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.status
   *
   * @return the value of role.status
   *
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.status
   *
   * @param status the value for role.status
   *
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.read_only
   *
   * @return the value of role.read_only
   *
   * @mbggenerated
   */
  public Boolean getReadOnly() {
    return readOnly;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.read_only
   *
   * @param readOnly the value for role.read_only
   *
   * @mbggenerated
   */
  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.row_version
   *
   * @return the value of role.row_version
   *
   * @mbggenerated
   */
  public Timestamp getRowVersion() {
    return rowVersion;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.row_version
   *
   * @param rowVersion the value for role.row_version
   *
   * @mbggenerated
   */
  public void setRowVersion(Timestamp rowVersion) {
    this.rowVersion = rowVersion;
  }
}