package bz.sunlight.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class Role implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.creator
   *
   * @mbggenerated
   */
  private String creator;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.enterprise_id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column role.row_version
   *
   * @mbggenerated
   */
  private Timestamp rowVersion;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table role
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.id
   *
   * @return the value of role.id
   *
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.id
   *
   * @param id the value for role.id
   *
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.name
   *
   * @return the value of role.name
   *
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.name
   *
   * @param name the value for role.name
   *
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.create_time
   *
   * @return the value of role.create_time
   *
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.create_time
   *
   * @param createTime the value for role.create_time
   *
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.creator
   *
   * @return the value of role.creator
   *
   * @mbggenerated
   */
  public String getCreator() {
    return creator;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.creator
   *
   * @param creator the value for role.creator
   *
   * @mbggenerated
   */
  public void setCreator(String creator) {
    this.creator = creator == null ? null : creator.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.enterprise_id
   *
   * @return the value of role.enterprise_id
   *
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.enterprise_id
   *
   * @param enterpriseId the value for role.enterprise_id
   *
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.status
   *
   * @return the value of role.status
   *
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.status
   *
   * @param status the value for role.status
   *
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column role.row_version
   *
   * @return the value of role.row_version
   *
   * @mbggenerated
   */
  public Timestamp getRowVersion() {
    return rowVersion;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column role.row_version
   *
   * @param rowVersion the value for role.row_version
   *
   * @mbggenerated
   */
  public void setRowVersion(Timestamp rowVersion) {
    this.rowVersion = rowVersion;
  }
}