package bz.sunlight.entity;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

public class User implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.id
   *
   * @mbggenerated
   */
  private String id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.name
   *
   * @mbggenerated
   */
  private String name;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.open_id
   *
   * @mbggenerated
   */
  private String openId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.username
   *
   * @mbggenerated
   */
  private String username;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.creator
   *
   * @mbggenerated
   */
  private String creator;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.modify_time
   *
   * @mbggenerated
   */
  private Date modifyTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.enterprise_id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user.row_version
   *
   * @mbggenerated
   */
  private Timestamp rowVersion;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.id
   *
   * @return the value of user.id
   * @mbggenerated
   */
  public String getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.id
   *
   * @param id the value for user.id
   * @mbggenerated
   */
  public void setId(String id) {
    this.id = id == null ? null : id.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.name
   *
   * @return the value of user.name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.name
   *
   * @param name the value for user.name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.open_id
   *
   * @return the value of user.open_id
   * @mbggenerated
   */
  public String getOpenId() {
    return openId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.open_id
   *
   * @param openId the value for user.open_id
   * @mbggenerated
   */
  public void setOpenId(String openId) {
    this.openId = openId == null ? null : openId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.username
   *
   * @return the value of user.username
   * @mbggenerated
   */
  public String getUsername() {
    return username;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.username
   *
   * @param username the value for user.username
   * @mbggenerated
   */
  public void setUsername(String username) {
    this.username = username == null ? null : username.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.create_time
   *
   * @return the value of user.create_time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.create_time
   *
   * @param createTime the value for user.create_time
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.creator
   *
   * @return the value of user.creator
   * @mbggenerated
   */
  public String getCreator() {
    return creator;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.creator
   *
   * @param creator the value for user.creator
   * @mbggenerated
   */
  public void setCreator(String creator) {
    this.creator = creator == null ? null : creator.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.modify_time
   *
   * @return the value of user.modify_time
   * @mbggenerated
   */
  public Date getModifyTime() {
    return modifyTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.modify_time
   *
   * @param modifyTime the value for user.modify_time
   * @mbggenerated
   */
  public void setModifyTime(Date modifyTime) {
    this.modifyTime = modifyTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.enterprise_id
   *
   * @return the value of user.enterprise_id
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.enterprise_id
   *
   * @param enterpriseId the value for user.enterprise_id
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.status
   *
   * @return the value of user.status
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.status
   *
   * @param status the value for user.status
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user.row_version
   *
   * @return the value of user.row_version
   * @mbggenerated
   */
  public Timestamp getRowVersion() {
    return rowVersion;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user.row_version
   *
   * @param rowVersion the value for user.row_version
   * @mbggenerated
   */
  public void setRowVersion(Timestamp rowVersion) {
    this.rowVersion = rowVersion;
  }
}