package bz.sunlight.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class UserCredential implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.user_id
   *
   * @mbggenerated
   */
  private String userId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.username
   *
   * @mbggenerated
   */
  private String username;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.password
   *
   * @mbggenerated
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.enterprise_id
   *
   * @mbggenerated
   */
  private String enterpriseId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.enterprise_code
   *
   * @mbggenerated
   */
  private String enterpriseCode;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.status
   *
   * @mbggenerated
   */
  private Integer status;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_credential.row_version
   *
   * @mbggenerated
   */
  private Timestamp rowVersion;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user_credential
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.user_id
   *
   * @return the value of user_credential.user_id
   *
   * @mbggenerated
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.user_id
   *
   * @param userId the value for user_credential.user_id
   *
   * @mbggenerated
   */
  public void setUserId(String userId) {
    this.userId = userId == null ? null : userId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.username
   *
   * @return the value of user_credential.username
   *
   * @mbggenerated
   */
  public String getUsername() {
    return username;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.username
   *
   * @param username the value for user_credential.username
   *
   * @mbggenerated
   */
  public void setUsername(String username) {
    this.username = username == null ? null : username.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.password
   *
   * @return the value of user_credential.password
   *
   * @mbggenerated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.password
   *
   * @param password the value for user_credential.password
   *
   * @mbggenerated
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.enterprise_id
   *
   * @return the value of user_credential.enterprise_id
   *
   * @mbggenerated
   */
  public String getEnterpriseId() {
    return enterpriseId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.enterprise_id
   *
   * @param enterpriseId the value for user_credential.enterprise_id
   *
   * @mbggenerated
   */
  public void setEnterpriseId(String enterpriseId) {
    this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.enterprise_code
   *
   * @return the value of user_credential.enterprise_code
   *
   * @mbggenerated
   */
  public String getEnterpriseCode() {
    return enterpriseCode;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.enterprise_code
   *
   * @param enterpriseCode the value for user_credential.enterprise_code
   *
   * @mbggenerated
   */
  public void setEnterpriseCode(String enterpriseCode) {
    this.enterpriseCode = enterpriseCode == null ? null : enterpriseCode.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.status
   *
   * @return the value of user_credential.status
   *
   * @mbggenerated
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.status
   *
   * @param status the value for user_credential.status
   *
   * @mbggenerated
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_credential.row_version
   *
   * @return the value of user_credential.row_version
   *
   * @mbggenerated
   */
  public Timestamp getRowVersion() {
    return rowVersion;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_credential.row_version
   *
   * @param rowVersion the value for user_credential.row_version
   *
   * @mbggenerated
   */
  public void setRowVersion(Timestamp rowVersion) {
    this.rowVersion = rowVersion;
  }
}