package bz.sunlight.entity;

import java.io.Serializable;

public class UserRole implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_role.Role_Id
   *
   * @mbggenerated
   */
  private String roleId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_role.User_Id
   *
   * @mbggenerated
   */
  private String userId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user_role
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_role.Role_Id
   *
   * @return the value of user_role.Role_Id
   * @mbggenerated
   */
  public String getRoleId() {
    return roleId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_role.Role_Id
   *
   * @param roleId the value for user_role.Role_Id
   * @mbggenerated
   */
  public void setRoleId(String roleId) {
    this.roleId = roleId == null ? null : roleId.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_role.User_Id
   *
   * @return the value of user_role.User_Id
   * @mbggenerated
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_role.User_Id
   *
   * @param userId the value for user_role.User_Id
   * @mbggenerated
   */
  public void setUserId(String userId) {
    this.userId = userId == null ? null : userId.trim();
  }
}