package bz.sunlight.entity;

import java.io.Serializable;

public class WhiteList implements Serializable {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column white_list.api_id
   *
   * @mbggenerated
   */
  private String apiId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table white_list
   *
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column white_list.api_id
   *
   * @return the value of white_list.api_id
   * @mbggenerated
   */
  public String getApiId() {
    return apiId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column white_list.api_id
   *
   * @param apiId the value for white_list.api_id
   * @mbggenerated
   */
  public void setApiId(String apiId) {
    this.apiId = apiId == null ? null : apiId.trim();
  }
}